# =================================================================================================
#                                  All Rights Reserved.
# =================================================================================================
# File description:
#       .gitlab-ci.yml to set up CI workflow
#
# =================================================================================================
#    Date      Name                    Description of Change
# 25-Jan-2023  Wayne Shih              Initial create
# 25-Jan-2023  Wen Shih                Add a new job
# $HISTORY$
# =================================================================================================

hello-world:
  script:
    - echo "hello world, GitLab!!!"

run-unit-tests:
  script:
    - echo "running unit tests..."

  before_script:
    - echo "npm install"

  after_script:
    - echo "Job has finished. cleaning up..."
