# =================================================================================================
#                                  All Rights Reserved.
# =================================================================================================
# File description:
#       .gitlab-ci.yml to set up CI workflow
#
# =================================================================================================
#    Date      Name                    Description of Change
# 25-Jan-2023  Wayne Shih              Initial create
# 25-Jan-2023  Wen Shih                Add a new job
# 25-Jan-2023  Wayne Shih              Add a bad job
# 25-Jan-2023  Wayne Shih              Add stages
# 25-Jan-2023  Wayne Shih              Add dependency between stage jobs
# 25-Jan-2023  Wayne Shih              Run run.sh at hello-world
# 26-Jan-2023  Wayne Shih              Add only and expect branch to jobs
# $HISTORY$
# =================================================================================================

stages:
  - hello-world
  - install
  - linter-and-testing
  - build
  - deploy

hello-world:
  except:
    - main
    - dev
  stage: hello-world
  script:
    - echo "hello world, GitLab!!!"
    - bash ./run.sh

npm-install:
  stage: install
  script:
    - echo "npm install"

run-unit-tests:
  stage: linter-and-testing
  script:
    - echo "running unit tests..."

run-linter:
  stage: linter-and-testing
  script:
    - echo "running linter..."

build-service:
  only:
    - main
    - dev
  stage: build
  script:
    - echo "building service app..."

build-image:
  only:
    - main
    - dev
  stage: build
  needs:
    - build-service
  script:
    - echo "building docker image..."

deploy:
  only:
    - main
  stage: deploy
  script:
    - echo "deploying..."
